<Project>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>
    
    <!-- We want to do a bit of xunit magic. So let's add all test relevant packages in one central place -->
    <ItemGroup Condition="'$(IsTestProject)' == 'true'">
        <PackageReference Include="Scrutor"/>
        <PackageReference Include="Seq.Extensions.Logging"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.v3.extensibility.core" />
        <PackageReference Include="xunit.runner.visualstudio">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    </ItemGroup>
    
</Project>
