<Project>
    <ItemGroup>
        <PackageVersion Include="Antlr4.Runtime.Standard" Version="4.13.1" />
        <PackageVersion Include="Antlr4BuildTasks" Version="12.10.0" PrivateAssets="all" IncludeAssets="build" />
        <PackageVersion Include="Eto.Parse" Version="1.6.0" />
        <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" />
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit" Version="1.1.1"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.3.0"/>
        <PackageVersion Include="Microsoft.Extensions.AI" Version="9.10.0" />
        <PackageVersion Include="OpenAI" Version="2.5.0" />
        
        <!-- Testing & Logging & Development -->
        <PackageVersion Include="JetBrains.Annotations" Version="2025.2.2" />
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.9" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.14.2" />
        <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="1.8.4" />
        <PackageVersion Include="Seq.Extensions.Logging" Version="8.0.0" />
        <PackageVersion Include="Serilog" Version="4.3.0" />
        <PackageVersion Include="Serilog.Enrichers.AssemblyName" Version="2.0.0" />
        <PackageVersion Include="Serilog.Enrichers.Context" Version="4.6.5" />
        <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />
        <PackageVersion Include="Serilog.Settings.Configuration" Version="9.0.0" />
        <PackageVersion Include="Serilog.Sinks.ColoredConsole" Version="3.0.1" />
        <PackageVersion Include="Serilog.Sinks.Seq" Version="9.0.0" />
        <PackageVersion Include="Snapshooter.Xunit3" Version="1.0.1" />
        <PackageVersion Include="Toolbelt.Blazor.SpeechRecognition" Version="1.0.0" />
        <PackageVersion Include="xunit.v3" Version="3.1.0" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageVersion Include="xunit.v3.extensibility.core" Version="3.1.0" />
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit" Version="1.1.2" />
        <PackageVersion Include="Scrutor" Version="6.1.0" />
    </ItemGroup>
</Project>