<Project>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <WarningsAsErrors>true</WarningsAsErrors>
    </PropertyGroup>
    
    <!-- Set properties if project name ends with ".Tests" -->
    <Choose>
        <When Condition="$(MSBuildProjectName.ToLower().EndsWith('.tests'))">
            <PropertyGroup>
                <IsTestProject>true</IsTestProject>
            </PropertyGroup>
        </When>
        <Otherwise>
            <PropertyGroup>
                <IsTestProject>false</IsTestProject>
            </PropertyGroup>
        </Otherwise>
    </Choose>

    <ItemGroup Condition="'$(IsTestProject)' == 'true'">
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>
