namespace EtAlii.Ubigia.Lark;

/// <summary>
/// Represents the syntax parsed from Lark grammar definitions.
/// This class encapsulates the results of parsing, providing access
/// to parsed items, detected errors, and additional metadata.
/// </summary>
public partial class LarkParseSyntax
{
    public required bool IsValid { get; init; }

    /// Provides access to the collection of parsed items resulting from the Lark grammar processing.
    /// This property contains an array of `Item` objects that represent the individual components of the
    /// parsed syntax, such as rules, tokens, or other structural elements.
    /// The value of this property is determined during the parsing process and cannot be modified afterwards.
    public required Item[] Items { get; init; }

    /// Represents a collection of errors that were encountered during the parsing process.
    /// This property contains an array of string messages, each describing a specific error
    /// detected in the syntax or during processing of the input data.
    /// The errors include those generated by the parser as well as any additional
    /// syntax-related issues from imported dependencies.
    /// If no errors are found during parsing, this property will be an empty array.
    /// This property is initialized during the parsing process and cannot be modified afterwards.
    public required string[] Errors { get; init; }

    /// Represents the textual representation of the parsed syntax.
    /// This property contains a string that summarizes the parsed elements
    /// generated by processing Lark grammar definitions.
    /// It is constructed by concatenating the string output of all parsed items
    /// and is finalized during the parsing process.
    /// The text is trimmed of any trailing whitespace or line breaks.
    public required string Text { get; init; }
}