<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.AI" />
      <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
      <PackageReference Include="ModelContextProtocol.AspNetCore" />
      <PackageReference Include="ModelContextProtocolServer.Sse" />
      <PackageReference Include="OpenAI" />
    </ItemGroup>

</Project>
