<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\EtAlii.Text.Lark\EtAlii.Text.Lark.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="_Examples\**\*.lark">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="_Examples\**\*.txt">
            <DependentUpon>%(Filename).lark</DependentUpon>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="_Examples\**\*.expected">
            <DependentUpon>%(Filename).lark</DependentUpon>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
