<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>EtAlii.Text.Lark.Generators.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\EtAlii.Text.Lark.Generators\EtAlii.Text.Lark.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="DDD.UbiquitousLanguageRegistry.txt"/>
        <AdditionalFiles Include="DDD.UbiquitousLanguageRegistry.txt"/>
    </ItemGroup>

</Project>
