using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace EtAlii.Text.Lark.Generators.Tests;

public class ExampleSetupTests
{
    private const string ContextClassText = 
        @"""

        using System.Text.Lark;

        namespace TestNamespace;

        public class Person
        {
        }

        [Generators.Report]
        public partial class TestLarkContext : LarkSerializationContext
        {
        }
        """;

    private const string ExpectedGeneratedClassText = 
        @"""
        // <auto-generated/>

        using System;
        using System.Collections.Generic;

        namespace TestNamespace;

        partial class Vector3
        {
            public IEnumerable<string> Report()
            {
                yield return $""X:{this.X}"";
                yield return $""Y:{this.Y}"";
                yield return $""Z:{this.Z}"";
            }
        }
        """;

    [Fact(Skip = "Not yet")]
    public void GenerateReportMethod()
    {
        // Create an instance of the source generator.
        var generator = new SourceGeneratorWithAttributes();

        // Source generators should be tested using 'GeneratorDriver'.
        var driver = CSharpGeneratorDriver.Create(generator);

        // We need to create a compilation with the required source code.
        var compilation = CSharpCompilation.Create(nameof(SourceGeneratorWithAdditionalFilesTests),
            [
                CSharpSyntaxTree.ParseText(ContextClassText)],
            [
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            ]);

        // Run generators and retrieve all results.
        var runResult = driver.RunGenerators(compilation).GetRunResult();

        // All generated files can be found in 'RunResults.GeneratedTrees'.
        var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("Vector3.g.cs"));

        // Complex generators should be tested using text comparison.
        Assert.Equal(ExpectedGeneratedClassText, generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }
}