<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>7e5ca9e7-c8d4-418c-8b0c-c663a56172e2</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
        <PackageReference Include="Antlr4BuildTasks" Version="12.10.0" PrivateAssets="all" IncludeAssets="build" />
    </ItemGroup>

    <ItemGroup>
      <Antlr4 Include="Syntax\Antlr\*.g4" >
          <Listener>true</Listener>
          <Visitor>true</Visitor>
          <GAtn>true</GAtn>
          <Package>EtAlii.Ubigia.Lark</Package>
          <Error>true</Error>
      </Antlr4>
    </ItemGroup>
</Project>
