using System.Globalization;

namespace EtAlii.Ubigia.Lark;

/// <summary>
/// Provides a concrete visitor implementation for traversing and processing the parse tree
/// generated by the LarkParser.
/// </summary>
/// <remarks>
/// This class overrides methods from the base class <c>LarkParserBaseVisitor</c> to handle specific
/// rules in the Lark grammar. Each method is responsible for processing the respective parse
/// tree context and transforming it into the desired output.
/// Use this class to parse the Lark language syntax tree into structured objects.
/// </remarks>
public class LarkParserVisitor : LarkParserBaseVisitor<object>
{
    /// <inheritdoc />
    public override object VisitStart_(LarkParser.Start_Context context)
    {
        return context
            .item()
            .Select(i => (Item)base.VisitItem(i))
            .ToArray();
    }

    /// <inheritdoc />
    public override object VisitRule_(LarkParser.Rule_Context context)
    {
        var name = context.RULE().GetText();
        var parameters = (string[])VisitRule_params(context.rule_params());
        var priority = int.Parse(context.priority()?.NUMBER().GetText() ?? "0", CultureInfo.InvariantCulture);
        var expansions = (Alias[])VisitExpansions(context.expansions());
        return new Rule
        {
            Name = name,
            Parameters = parameters,
            Priority = priority,
            Expansions = expansions
        };
    }

    /// <inheritdoc />
    public override object VisitToken(LarkParser.TokenContext context)
    {
        var name = context.TOKEN().GetText();
        var parameters = (string[])VisitToken_params(context.token_params());
        var priority = int.Parse(context.priority()?.NUMBER().GetText() ?? "0", CultureInfo.InvariantCulture);
        var expansions = (Alias[])VisitExpansions(context.expansions());
        return new Token
        {
            Name = name,
            Parameters = parameters,
            Priority = priority,
            Expansions = expansions
        };
    }

    /// <inheritdoc />
    public override object VisitStatement(LarkParser.StatementContext context)
    {
        if (context.expansions() is { } expansions)
        {
            return new IgnoreStatement
            {
                Expansions = (Alias[])VisitExpansions(expansions)
            };
        }

        if (context.import_path() is { } importPath)
        {
            if (context.name_list() is { } nameList)
            {
                return new ImportStatement
                {
                    Path = importPath.GetText(),
                    Names = (string[])VisitName_list(nameList)
                };
            }

            return new ImportStatement
            {
                Path = importPath.GetText(),
                Names = context.name() is { Length: > 0 } name ? [ name[0].GetText() ] : []
            };
        }

        if (context.name() is { } names)
        {
            return new DeclareStatement
            {
                Names = names.Select(n => n.GetText()).ToArray()
            };
        }

        return new OverrideStatement
        {
            Rule = (Rule)VisitRule_(context.rule_())
        };
    }

    /// <inheritdoc />
    public override object VisitName_list(LarkParser.Name_listContext context)
    {
        return context
            .name()
            .Select(n => n.GetText())
            .ToArray();
    }

    /// <inheritdoc />
    public override object VisitExpansions(LarkParser.ExpansionsContext context)
    {
        return context.alias()
            .Select(a => (Alias)VisitAlias(a))
            .ToArray();
    }

    /// <inheritdoc />
    public override object VisitAlias(LarkParser.AliasContext context)
    {
        var expansion = (Expansion)VisitExpansion(context.expansion());
        var rule = context.RULE()?.GetText() ?? string.Empty;
        return new Alias
        {
            Expansion = expansion,
            Rule = rule,
        };
    }

    /// <inheritdoc />
    public override object VisitExpansion(LarkParser.ExpansionContext context)
    {
        var expressions = context
            .expr()
            .Select(e => (Expression)VisitExpr(e))
            .ToArray();
        return new Expansion
        {
            Expressions = expressions
        };
    }

    /// <inheritdoc />
    public override object VisitExpr(LarkParser.ExprContext context)
    {
        return new Expression
        {
            Atom = (Atom)VisitAtom(context.atom())
        };
    }

    /// <inheritdoc />
    public override object VisitRule_params(LarkParser.Rule_paramsContext context)
    {
        return context.RULE().Select(r => r.GetText()).ToArray();
    }

    /// <inheritdoc />
    public override object VisitToken_params(LarkParser.Token_paramsContext context)
    {
        return context.TOKEN().Select(r => r.GetText()).ToArray();
    }

    /// <inheritdoc />
    public override object VisitName(LarkParser.NameContext context)
    {
        return context.GetText();
    }

    /// <inheritdoc />
    public override object VisitValue(LarkParser.ValueContext context)
    {
        var strings = context.STRING() ?? [];
        if (strings.Length == 2)
        {
            return new RangeValue
            {
                From = strings[0].GetText(),
                To = strings[1].GetText()
            };
        }

        if (context.REGEXP() is { } regexp)
        {
            return new RegexValue { Regex = regexp.GetText() };
        }

        var values = context.value();
        if (values.Length > 0)
        {
            var name = context.name().GetText();
            return new CollectionValue
            {
                Name = name,
                Values = values
                    .Select(v => (Value)VisitValue(v))
                    .ToArray()
            };
        }
        if (context.name() is { } n)
        {
            return new NameValue
            {
                Name = n.GetText()
            };
        }
        
        return new NameValue
        {
            Name = context.STRING(0).GetText()
        };
    }

    /// <inheritdoc />
    public override object VisitAtom(LarkParser.AtomContext context)
    {
        if (context.value() is { } value)
        {
            var v = (Value)VisitValue(value);
            return new ValueAtom { Value = v };
        }

        if (context.GetText().StartsWith("["))
        {
            return new ArrayAtom
            {
                Expansions = (Alias[])VisitExpansions(context.expansions())
            };
        }
        return new ParametersAtom
        {
            Expansions = (Alias[])VisitExpansions(context.expansions())
        };
    }
}