fun: NON_WHITESPACE | MESCAPED_STRINGD | MESCAPED_STRING //MYSTRING //ESCAPED_STRING
?func: fun | "(" (call | func | lambda_ | def_)  ")"
def_: DEF
DEF . 2: /def _(.|\n)*\n\s*\r?\n/
lambda_: LAMBDA
LAMBDA . 1: /lambda (?:[^()]*\(.*?\)[^()]*|[^()]+)/
partial: func "{" ((func | partial | reverse_partial | call)+ | def_) "}"
reverse_partial: func "[" (func | partial | reverse_partial | call)+ "]"
?arg: func | partial | reverse_partial | "(" call ")"
trailing1: ("{" func* "}")?
trailing2: _trailing3
_trailing3: func | call | partial | reverse_partial
call_nt: call_nt? arg* "." func trailing1 -> call
call_t: call_nt? arg* func "\\" trailing2 -> call
call_p: call_nt? arg* (p | star_p) _trailing3
p: "|"
star_p: "*|"
?call: call_nt | call_t | call_p

start: call | partial | func

NON_WHITESPACE: /(?![\\.|\*\|])[^\s{}|\(\)"\[\]]+( |\n)/
MYSTRING: /r?'[^']*'/

_MSTRING_INNER: /.*?/
_MSTRING_ESC_INNER: _MSTRING_INNER /(?<!\\)(\\\\)*?/

MESCAPED_STRING : "r"? "'" _MSTRING_ESC_INNER "'"
MESCAPED_STRINGD : "r"? "\"" _MSTRING_ESC_INNER "\""
//NON_WHITESPACE: /r?'[^']*'|(?![\\.|\*\|])[^\s{}|\(\)"]+/
// https://chatgpt.com/share/674ec08f-50e8-8003-99fb-3312c9760e4e


%import common.CNAME -> NAME
%import common.WS
//%import common.SIGNED_NUMBER
%ignore WS
%import common.ESCAPED_STRING

