using System.Globalization;

namespace EtAlii.Ubigia.Lark;

/// <summary>
/// Provides a concrete visitor implementation for traversing and processing the parse tree
/// generated by the LarkParser.
/// </summary>
/// <remarks>
/// This class overrides methods from the base class <c>LarkParserBaseVisitor</c> to handle specific
/// rules in the EBNF/Lark syntax. Each method is responsible for processing the respective parse
/// tree context and transforming it into the desired output.
/// Use this class to parse the EBNF/Lark language syntax tree into structured objects.
/// </remarks>
public partial class EbnfParserVisitor : LarkParserBaseVisitor<object>
{
    private readonly IImportSource _importSource;

    public EbnfParserVisitor(IImportSource importSource)
    {
        _importSource = importSource;
    }

    /// <inheritdoc />
    public override object VisitStart_(LarkParser.Start_Context context)
    {
        return context
            .item()
            .Select(i => (Item)base.VisitItem(i))
            .ToArray();
    }

    /// <inheritdoc />
    public override object VisitAlias(LarkParser.AliasContext context)
    {
        var expansion = (Expansion)VisitExpansion(context.expansion());
        var rule = context.RULE()?.GetText() ?? string.Empty;
        return new Alias
        {
            Expansion = expansion,
            Name = rule,
        };
    }

    /// <inheritdoc />
    public override object VisitExpr(LarkParser.ExprContext context)
    {
        if (context.OP() is { } op)
        {
            return new AtomWithOperatorExpression
            {
                Atom = (Atom)VisitAtom(context.atom()),
                Operator = op.GetText()
            };
        }

        var numbers = context.NUMBER();
        if (numbers.Length == 0)
        {
            return new AtomOnlyExpression
            {
                Atom = (Atom)VisitAtom(context.atom()),
            };
        }
        if (numbers.Length == 1)
        {
            return new TildeExpression
            {
                Atom = (Atom)VisitAtom(context.atom()),
                From = int.Parse(numbers[0].GetText(), CultureInfo.InvariantCulture)
            };
        }

        return new TildeRangeExpression
        {
            Atom = (Atom)VisitAtom(context.atom()),
            From = int.Parse(numbers[0].GetText(), CultureInfo.InvariantCulture),
            To = int.Parse(numbers[1].GetText(), CultureInfo.InvariantCulture)
        };
    }

    /// <inheritdoc />
    public override object VisitName(LarkParser.NameContext context)
    {
        return context.GetText();
    }

    /// <inheritdoc />
    public override object VisitValue(LarkParser.ValueContext context)
    {
        var strings = context.STRING() ?? [];
        if (strings.Length == 2)
        {
            return new RangeValue
            {
                From = strings[0].Symbol.Text,
                To = strings[1].Symbol.Text
            };
        }

        if (context.REGEXP() is { } regexp)
        {
            return new RegexValue { Regex = regexp.GetText() };
        }

        var values = context.value();
        if (values.Length > 0)
        {
            var name = context.name().GetText();
            return new NamedValueList
            {
                Name = name,
                Values = values
                    .Select(v => (Value)VisitValue(v))
                    .ToArray()
            };
        }
        if (context.name() is { } n)
        {
            return new NameValue
            {
                Name = n.GetText()
            };
        }
        
        return new NameValue
        {
            Name = context.STRING(0).GetText()
        };
    }

    /// <inheritdoc />
    public override object VisitAtom(LarkParser.AtomContext context)
    {
        if (context.value() is { } value)
        {
            var v = (Value)VisitValue(value);
            return new ValueAtom { Value = v };
        }

        if (context.GetText().StartsWith("["))
        {
            return new ArrayAtom
            {
                Expansions = (Alias[])VisitExpansions(context.expansions())
            };
        }
        return new ParametersAtom
        {
            Expansions = (Alias[])VisitExpansions(context.expansions())
        };
    }
}