<Project Sdk="Microsoft.NET.Sdk">


    <ItemGroup>
      <PackageReference Include="Eto.Parse" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Antlr4.Runtime.Standard" />
        <PackageReference Include="Antlr4BuildTasks" PrivateAssets="all" IncludeAssets="build" />
    </ItemGroup>

    <ItemGroup>
        <Antlr4 Include="_Old\Syntax\Antlr\*.g4" >
            <Listener>true</Listener>
            <Visitor>true</Visitor>
            <GAtn>true</GAtn>
            <Package>EtAlii.Text.Lark._Old</Package>
            <Error>true</Error>
        </Antlr4>
    </ItemGroup>
    
</Project>
